import os
from selene import browser, be, have, command


def test_check_form():
    browser.open('/automation-practice-form')
    browser.element('#firstName').should(be.blank).type('Ivan')
    browser.element('#lastName').should(be.blank).type('Ivanov')
    browser.element('#userEmail').should(be.blank).type('ivanov@gmail.com')
    browser.element('[for="gender-radio-2"]').double_click()
    browser.element('#userNumber').should(be.blank).type('7895454647')
    browser.element('#dateOfBirthInput').click()
    browser.element('.react-datepicker__month-select').click()
    browser.element('.react-datepicker__month-select [value = "9"]').click()
    browser.element('.react-datepicker__year-select').click()
    browser.element('.react-datepicker__year-select [value = "2000"]').perform(command.js.scroll_into_view).click()
    browser.element('.react-datepicker__day--015').click()
    browser.element('#subjectsInput').should(be.blank).type('h').press_enter()
    browser.element('[for=hobbies-checkbox-2]').click()
    browser.element('#uploadPicture').send_keys(os.path.abspath('resourses/test.png'))
    browser.element('#currentAddress').should(be.blank).type('Ivanovskaia, 17').press_enter()
    browser.element('#react-select-3-input').type('u').press_enter()
    browser.element('#react-select-4-input').type('a').press_enter()
    browser.element('#submit').press_enter()
    browser.all('.table>tbody>tr')[0].should(have.exact_text('Student Name Ivan Ivanov'))
    browser.all('.table>tbody>tr')[1].should(have.exact_text('Student Email ivanov@gmail.com'))
    browser.all('.table>tbody>tr')[2].should(have.exact_text('Gender Female'))
    browser.all('.table>tbody>tr')[3].should(have.exact_text('Mobile 7895454647'))
    browser.all('.table>tbody>tr')[4].should(have.exact_text('Date of Birth 15 October,2000'))
    browser.all('.table>tbody>tr')[5].should(have.exact_text('Subjects Hindi'))
    browser.all('.table>tbody>tr')[6].should(have.exact_text('Hobbies Reading'))
    browser.all('.table>tbody>tr')[7].should(have.exact_text('Picture test.png'))
    browser.all('.table>tbody>tr')[8].should(have.exact_text('Address Ivanovskaia, 17'))
    browser.all('.table>tbody>tr')[9].should(have.exact_text('State and City Uttar Pradesh Agra'))
    browser.element('#closeLargeModal').double_click()
